<?php

$title = "Marmitas da Dona Rita";

$items = array(
    0 => array('id' => '1', 
    'figura' => 'img/muqueca.png',
    'marmita' => 'Muqueca de Cação', 
    'tamanho' => 'Tamanho do Prato', 
    'detalhes' => '<h3>Com ervas frescas... </h3>Garantimos que a moqueca seja ainda mais saborosa, essa receita temperamos com uma combinação de ervas frescas.<br/> Usamos hortelã, limão, manjericão, cebolinha e coentro.', 
    'preco' => 'R$20,00'),
    1 => array('id' => '2', 
    'figura' => 'img/carnepanela.png', 
    'marmita' => 'Carne de panela', 
    'tamanho' => 'Tamanho do Prato', 
    'detalhes' =>'<h3>Carne na panela de pressão...</h3> Junto com batata, mandioquinha, cenoura e alguns temperos especiais deixam o molho e a carne com aquele sabor inesquecível.', 
    'preco' => '20'),
    2 => array('id' => '3', 
    'figura' => 'img/prato5.png', 
    'marmita' => 'Nome do Prato3',
    'tamanho' => 'Tamanho do Prato', 
    'detalhes' => '',
    'preco' => '20'),
    3 => array('id' => '4', 
    'figura' => 'img/prato1.png', 
    'marmita' => 'Nome do Prato4', 
    'tamanho' => 'Tamanho do Prato',
    'detalhes' => '',
    'preco' => '20'),
    4 => array('id' => '5', 
    'figura' => 'https://images.unsplash.com/photo-1540432797114-187727adf19b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80', 
    'marmita' => 'Nome do Prato5', 
    'tamanho' => 'Tamanho do Prato',
    'detalhes' => '',
    'preco' => '20'),
    5 => array('id' => '6', 
    'figura' => 'https://images.unsplash.com/photo-1528738064262-9f834cbdfda1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80', 
    'marmita' => 'Nome do Prato6', 
    'tamanho' => 'Tamanho do Prato',
    'detalhes' => '',
    'preco' => '20'),
    6 => array('id' => '7', 
    'figura' => 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80', 
    'marmita' => 'Nome do Prato7', 
    'tamanho' => 'Tamanho do Prato',
    'detalhes' => '',
    'preco' => '20'),
);

